import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StartUp-Summer',
  description: 'Generated by create next app',
}
/*export const link = {
  href: 'https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap',
  rel: 'stylesheet',
}*/


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>{ children }</body>
    </html>
  )
}
